-- Centralized admin notifications generated from key user events.

CREATE OR REPLACE FUNCTION public.is_backoffice_actor()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  WITH claims AS (
    SELECT auth.jwt() AS j
  ),
  normalized AS (
    SELECT
      lower(trim(coalesce(j -> 'user_metadata' ->> 'account_type', ''))) AS user_account_type,
      lower(trim(coalesce(j -> 'app_metadata' ->> 'account_type', ''))) AS app_account_type,
      lower(trim(coalesce(j -> 'user_metadata' ->> 'role', ''))) AS user_role,
      lower(trim(coalesce(j -> 'app_metadata' ->> 'role', ''))) AS app_role,
      lower(trim(coalesce(j -> 'user_metadata' ->> 'is_admin', ''))) AS user_is_admin,
      lower(trim(coalesce(j -> 'app_metadata' ->> 'is_admin', ''))) AS app_is_admin,
      coalesce(j -> 'app_metadata' -> 'roles', '[]'::jsonb) AS app_roles
    FROM claims
  )
  SELECT
    user_account_type IN ('agency', 'admin', 'super_admin', 'superadmin')
    OR app_account_type IN ('agency', 'admin', 'super_admin', 'superadmin')
    OR user_role IN ('agency', 'admin', 'super_admin', 'superadmin')
    OR app_role IN ('agency', 'admin', 'super_admin', 'superadmin')
    OR user_is_admin IN ('true', '1')
    OR app_is_admin IN ('true', '1')
    OR EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(app_roles) AS role(value)
      WHERE lower(trim(role.value)) IN ('agency', 'admin', 'super_admin', 'superadmin')
    )
  FROM normalized;
$$;

CREATE TABLE IF NOT EXISTS admin_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL,
  icon_key text NOT NULL DEFAULT 'bell',
  title text NOT NULL,
  body text,
  href text NOT NULL DEFAULT '/admin/protected',
  entity_table text,
  entity_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_notifications_created_at_idx
  ON admin_notifications (created_at DESC);

CREATE INDEX IF NOT EXISTS admin_notifications_unread_created_idx
  ON admin_notifications (is_read, created_at DESC);

CREATE INDEX IF NOT EXISTS admin_notifications_event_type_idx
  ON admin_notifications (event_type);

ALTER TABLE IF EXISTS admin_notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_notifications_select_backoffice ON admin_notifications;
CREATE POLICY admin_notifications_select_backoffice
  ON admin_notifications
  FOR SELECT
  TO authenticated
  USING (public.is_backoffice_actor());

DROP POLICY IF EXISTS admin_notifications_update_backoffice ON admin_notifications;
CREATE POLICY admin_notifications_update_backoffice
  ON admin_notifications
  FOR UPDATE
  TO authenticated
  USING (public.is_backoffice_actor())
  WITH CHECK (public.is_backoffice_actor());

CREATE OR REPLACE FUNCTION public.admin_notify(
  p_event_type text,
  p_title text,
  p_body text DEFAULT NULL,
  p_href text DEFAULT '/admin/protected',
  p_icon_key text DEFAULT 'bell',
  p_entity_table text DEFAULT NULL,
  p_entity_id text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.admin_notifications (
    event_type,
    icon_key,
    title,
    body,
    href,
    entity_table,
    entity_id,
    metadata
  )
  VALUES (
    coalesce(nullif(trim(p_event_type), ''), 'event'),
    coalesce(nullif(trim(p_icon_key), ''), 'bell'),
    coalesce(nullif(trim(p_title), ''), 'Nouvel evenement'),
    nullif(trim(coalesce(p_body, '')), ''),
    coalesce(nullif(trim(p_href), ''), '/admin/protected'),
    nullif(trim(coalesce(p_entity_table, '')), ''),
    nullif(trim(coalesce(p_entity_id, '')), ''),
    coalesce(p_metadata, '{}'::jsonb)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_admin_notify_viewing_request_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  payload jsonb := to_jsonb(NEW);
  row_id text := coalesce(payload ->> 'id', '');
  customer_name text := nullif(trim(coalesce(payload ->> 'name', '')), '');
  property_ref text := nullif(trim(coalesce(payload ->> 'property_ref', '')), '');
BEGIN
  PERFORM public.admin_notify(
    'viewing_request_created',
    'Nouvelle demande de visite',
    concat_ws(' | ',
      CASE WHEN customer_name IS NOT NULL THEN 'Client: ' || customer_name ELSE NULL END,
      CASE WHEN property_ref IS NOT NULL THEN 'REF: ' || property_ref ELSE NULL END
    ),
    CASE
      WHEN row_id <> '' THEN '/admin/protected/leads/visits/plan/' || row_id
      ELSE '/admin/protected/leads/visits'
    END,
    'calendar-clock',
    'viewing_requests',
    nullif(row_id, ''),
    jsonb_build_object(
      'property_ref', property_ref,
      'name', customer_name,
      'phone', nullif(trim(coalesce(payload ->> 'phone', '')), '')
    )
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_admin_notify_owner_lead_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  payload jsonb := to_jsonb(NEW);
  row_id text := coalesce(payload ->> 'id', '');
  intent text := lower(trim(coalesce(payload ->> 'intent', '')));
  customer_name text := nullif(trim(coalesce(payload ->> 'name', '')), '');
  property_type text := nullif(trim(coalesce(payload ->> 'property_type', '')), '');
  destination text := CASE
    WHEN intent IN ('agency_deposit', 'depot_tiers', 'third_party_upload', 'third_party')
      THEN '/admin/protected/leads/depot-tiers'
    ELSE '/admin/protected/leads/owners'
  END;
  title text := CASE
    WHEN intent IN ('agency_deposit', 'depot_tiers', 'third_party_upload', 'third_party')
      THEN 'Nouveau depot agence'
    ELSE 'Nouveau lead proprietaire'
  END;
BEGIN
  PERFORM public.admin_notify(
    CASE
      WHEN intent IN ('agency_deposit', 'depot_tiers', 'third_party_upload', 'third_party')
        THEN 'agency_deposit_created'
      ELSE 'owner_lead_created'
    END,
    title,
    concat_ws(' | ',
      CASE WHEN customer_name IS NOT NULL THEN 'Contact: ' || customer_name ELSE NULL END,
      CASE WHEN property_type IS NOT NULL THEN 'Type: ' || property_type ELSE NULL END
    ),
    destination,
    CASE
      WHEN intent IN ('agency_deposit', 'depot_tiers', 'third_party_upload', 'third_party')
        THEN 'building-2'
      ELSE 'house-plus'
    END,
    'owner_leads',
    nullif(row_id, ''),
    jsonb_build_object(
      'intent', nullif(intent, ''),
      'name', customer_name,
      'property_type', property_type
    )
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_admin_notify_short_stay_reservation_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  payload jsonb := to_jsonb(NEW);
  row_id text := coalesce(payload ->> 'id', '');
  property_ref text := nullif(trim(coalesce(payload ->> 'property_ref', '')), '');
  check_in_date text := nullif(trim(coalesce(payload ->> 'check_in_date', '')), '');
  check_out_date text := nullif(trim(coalesce(payload ->> 'check_out_date', '')), '');
BEGIN
  PERFORM public.admin_notify(
    'short_stay_reservation_created',
    'Nouvelle reservation court sejour',
    concat_ws(' | ',
      CASE WHEN property_ref IS NOT NULL THEN 'REF: ' || property_ref ELSE NULL END,
      CASE
        WHEN check_in_date IS NOT NULL AND check_out_date IS NOT NULL
          THEN check_in_date || ' -> ' || check_out_date
        ELSE NULL
      END
    ),
    '/admin/protected/leads/reservations',
    'hotel',
    'short_stay_reservations',
    nullif(row_id, ''),
    jsonb_build_object(
      'property_ref', property_ref,
      'check_in_date', check_in_date,
      'check_out_date', check_out_date
    )
  );
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF to_regclass('public.viewing_requests') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS trg_admin_notify_viewing_request_insert ON public.viewing_requests';
    EXECUTE 'CREATE TRIGGER trg_admin_notify_viewing_request_insert
      AFTER INSERT ON public.viewing_requests
      FOR EACH ROW
      EXECUTE FUNCTION public.trg_admin_notify_viewing_request_insert()';
  END IF;

  IF to_regclass('public.owner_leads') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS trg_admin_notify_owner_lead_insert ON public.owner_leads';
    EXECUTE 'CREATE TRIGGER trg_admin_notify_owner_lead_insert
      AFTER INSERT ON public.owner_leads
      FOR EACH ROW
      EXECUTE FUNCTION public.trg_admin_notify_owner_lead_insert()';
  END IF;

  IF to_regclass('public.short_stay_reservations') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS trg_admin_notify_short_stay_reservation_insert ON public.short_stay_reservations';
    EXECUTE 'CREATE TRIGGER trg_admin_notify_short_stay_reservation_insert
      AFTER INSERT ON public.short_stay_reservations
      FOR EACH ROW
      EXECUTE FUNCTION public.trg_admin_notify_short_stay_reservation_insert()';
  END IF;
END
$$;
