CREATE TABLE IF NOT EXISTS agency_visit_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  viewing_request_id uuid NOT NULL,
  agency_email text NOT NULL,
  agency_name text,
  agency_whatsapp text,
  property_ref text NOT NULL,
  property_title text,
  property_location text,
  property_price text,
  visit_preferred_date text,
  visit_preferred_time text,
  visit_status text NOT NULL DEFAULT 'scheduled',
  whatsapp_message text NOT NULL,
  whatsapp_link text,
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS agency_visit_notifications_viewing_request_uidx
  ON agency_visit_notifications (viewing_request_id);

CREATE INDEX IF NOT EXISTS agency_visit_notifications_agency_email_created_idx
  ON agency_visit_notifications (agency_email, created_at DESC);

ALTER TABLE IF EXISTS agency_visit_notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agency_visit_notifications_select_own ON agency_visit_notifications;
CREATE POLICY agency_visit_notifications_select_own
  ON agency_visit_notifications
  FOR SELECT
  TO authenticated
  USING (
    lower(coalesce(agency_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
