export const ORAN_COMMUNES = [
  "Oran",
  "Bir El Djir",
  "Es Senia",
  "Arzew",
  "Bethioua",
  "Gdyel",
  "Hassi Bounif",
  "Hassi Ben Okba",
  "Hassi Mefsoukh",
  "Sidi Chami",
  "Ben Freha",
  "Oued Tlelat",
  "El Kerma",
  "Ain El Turk",
  "Bousfer",
  "El Ancor",
  "Mers El Kebir",
  "Boutlelis",
  "Ain Biya",
  "Marsat El Hadjadj",
  "Sidi Ben Yebka",
  "Tafraoui",
  "Messerghine",
] as const;

export const DEFAULT_ORAN_QUARTIERS = [
  "Akid Lotfi",
  "Canastel",
  "Hai Sabah",
  "USTO",
  "Maraval",
  "M'dina Jdida",
  "Es Senia Centre",
  "El Yasmine",
  "Belgaid",
  "Hai El Badr",
  "Sidi El Bachir",
  "Les Amandiers",
  "Eckmuhl",
  "Gambetta",
  "Plateau",
  "Karguentah",
  "Miramar",
  "Bouisseville",
  "Trouville",
  "Kristel",
  "Douar Belgaid",
] as const;
